/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Ardiansyah
 */
public class DashboardOwner extends javax.swing.JPanel {

    /**
     * Creates new form DashboardOwner
     */
    public DashboardOwner() {
        initComponents();
        btnManajemenProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdukForm pf = new ProdukForm();
                pf.setVisible(true);
                // Also close or hide the current dashboard window if desired. Let's keep dashboard open or dispose it. Usually keeping it open is fine, but disposing/closing it makes it cleaner.
                // Let's close it so only one window is open at a time.
                java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(DashboardOwner.this);
                if (win != null) {
                    win.dispose();
                }
            }
        });
        btnLaporanPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPenjualanHarianForm lpf = new LaporanPenjualanHarianForm();
                lpf.setVisible(true);
                java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(DashboardOwner.this);
                if (win != null) {
                    win.dispose();
                }
            }
        });
        btnLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPenjualanBulananForm lpf = new LaporanPenjualanBulananForm();
                lpf.setVisible(true);
                java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(DashboardOwner.this);
                if (win != null) {
                    win.dispose();
                }
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(DashboardOwner.this);
                if (win != null) {
                    win.dispose();
                }
                new LoginForm().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManajemenProduk = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnLaporanPenjualan = new javax.swing.JButton();
        btnLaporanPenjualan1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("OriTeh Sapuro - Owner Dashboard");

        btnManajemenProduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManajemenProduk.setText("Manajemen Produk");

        btnLogout.setText("Logout");

        btnLaporanPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLaporanPenjualan.setText("Laporan Penjualan Bulanan");

        btnLaporanPenjualan1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLaporanPenjualan1.setText("Laporan Penjualan Harian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManajemenProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporanPenjualan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporanPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(btnManajemenProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaporanPenjualan1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLaporanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnLogout)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporanPenjualan;
    private javax.swing.JButton btnLaporanPenjualan1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManajemenProduk;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
